import '/src/js/fetchFilms';
import '/src/js/fetchSearchMovies'
import '/src/js/partials/modal-auth';
import '/src/js/partials/mobile-auth';
import '/src/js/auth';
import '/src/js/renderTrends';
import '/src/js/buildTrends';
import '/src/js/switch-day-night';
import '/src/js/arrow_top';
import '/src/js/local-storage';
import '/src/js/loader';
import '/src/js/noElementsPlug';
import '/src/js/key-url';
import '/src/js/modal-movie-card-close';
import '/src/js/modal-movie-card';
import '/src/js/modal-movie-card-open';
import '/src/js/modal-team'; 
